apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: order-service
    newName: order-service
    newTag: latest
  - name: payment-service
    newName: payment-service
    newTag: latest
  - name: erp-service
    newName: erp-service
    newTag: latest

patchesStrategicMerge:
  - service-patches.yaml