apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: order-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/order-service
    newTag: latest
  - name: payment-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/payment-service
    newTag: latest
  - name: erp-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/erp-service
    newTag: latest