apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  ORDER_DB_USERNAME: "order"
  ORDER_DB_PASSWORD: "password"
  PAYMENT_DB_USERNAME: "payment"
  PAYMENT_DB_PASSWORD: "password"
  JWT_SECRET: "demo-secret-key-for-local-development-only-replace-in-production"
  SLACK_WEBHOOK_URL: ""
  REDIS_PASSWORD: ""