apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- postgres-order.yaml
- postgres-payment.yaml
- redis.yaml
- kafka.yaml
- vault.yaml
- zipkin.yaml
- order-service.yaml
- payment-service.yaml
- erp-service.yaml